name: CI

on:
  push:
    branches: [ v3.0 ]
    tags: [ 'v*' ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.png'
      - '**/*.svg'
      - '**/*.jpg'
      - '**/*.jpeg'
  pull_request:
    branches: [ v3.0 ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # allow commit message opt-out
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Py${{ matrix.python }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install package and test deps
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
          pip install pytest

      - name: Run tests
        env:
          PYTHONUTF8: "1"
        run: pytest -q

      - name: Upload pytest cache (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-cache-${{ matrix.os }}-py${{ matrix.python }}
          path: .pytest_cache
          if-no-files-found: ignore
