name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Py${{ matrix.python }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install package and test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"

      - name: Run tests
        run: pytest -q
        env:
          PYTHONUTF8: "1"

      - name: Upload pytest cache (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-cache-${{ matrix.os }}-py${{ matrix.python }}
          path: .pytest_cache
          if-no-files-found: ignore
          
# .github/workflows/ci.yml
on:
  push:
    branches: [ v3.0 ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ v3.0 ]
