name: Docs
on:
  push:
    branches: [ main, v3.0 ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing to gh-pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs-material mike
      - name: Deploy versioned docs with mike
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            mike deploy --push 2.x
            mike set-default --push 2.x
          else
            mike deploy --push --update-aliases 3.0 latest
            mike set-default --push latest
          fi
