name: docs
on:
  push:
    branches: [ v3.0 ]
    paths:
      - 'docs/**'
      - 'mkdocs.yaml'
      - '.github/workflows/docs.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow push to gh-pages
    concurrency:
      group: docs-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # mike needs history to switch branches
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install mike mkdocs mkdocs-material
      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Deploy docs (version + alias)
        run: |
          mike deploy --push --update-aliases 3.0 latest
          mike set-default --push latest
